# Generated by Django 6.0.2 on 2026-03-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=300, unique=True)),
                ('img', models.ImageField(upload_to='static/media/blog')),
                ('des', models.CharField(max_length=600)),
            ],
        ),
    ]
