# Generated by Django 6.0.2 on 2026-03-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=300, unique=True)),
                ('img', models.ImageField(upload_to='static/media/')),
                ('des', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='LifestylePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=300, unique=True)),
                ('img', models.ImageField(upload_to='static/media/blog')),
                ('des', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=300, unique=True)),
                ('img', models.ImageField(upload_to='static/media/blog')),
                ('des', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='TechnologyPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=300, unique=True)),
                ('img', models.ImageField(upload_to='static/media/tech')),
                ('des', models.CharField(max_length=600)),
            ],
        ),
    ]
