# Generated by Django 6.0.2 on 2026-03-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_designpost_lifestylepost_programmingpost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designpost',
            name='img',
            field=models.ImageField(upload_to='design/'),
        ),
        migrations.AlterField(
            model_name='lifestylepost',
            name='img',
            field=models.ImageField(upload_to='lifestyle/'),
        ),
        migrations.AlterField(
            model_name='postblog',
            name='img',
            field=models.ImageField(upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='programmingpost',
            name='img',
            field=models.ImageField(upload_to='programming/'),
        ),
        migrations.AlterField(
            model_name='technologypost',
            name='img',
            field=models.ImageField(upload_to='tech/'),
        ),
    ]
